[package]
name = "jcblocktui"
version = "0.1.0"
description = "A TUI Block Game"
authors = ["Justin Cromer"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
jcblocks =  "0.1.0"
